version: '3.8'
services:
  db:
    container_name: pg_container_book_rksp7
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"