version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ./frontend/front-prac5
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./frontend/front-prac5/:/usr/src/app
  #     - ./frontend/front-prac5/node_modules:/usr/src/app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "85:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app1:
    image: ant1k/prac5
    container_name: app1
    env_file:
      - prod.env

  app2:
    image: ant1k/prac5
    container_name: app2
    env_file:
      - prod.env

  app3:
    image: ant1k/prac5
    container_name: app3
    env_file:
      - prod.env

  app4:
    image: ant1k/prac5
    container_name: app4
    env_file:
      - prod.env


volumes:
  postgres_data:
  node_modules: